import {defineArrayMember, defineField, defineType} from 'sanity'
import {bilingualRichText, bilingualString, languageGroups} from '../helpers'

export const postOccupancyPage = defineType({
  name: 'postOccupancyPage',
  title: 'Post occupancy evaluation page',
  type: 'document',
  groups: languageGroups,
  fields: [
    ...bilingualString('title', 'Page title'),
    ...bilingualRichText(
      'introduction',
      'Introduction',
      'Keep the three existing paragraphs in their current order.',
    ),
    ...bilingualString('residentVoicesTitle', 'Resident voices heading'),
    defineField({
      name: 'imageCaptionsEn',
      title: 'Case study image captions (English)',
      type: 'array',
      group: 'english',
      description: 'Each caption is attached to a permanent image ID. Sorting is disabled.',
      options: {
        sortable: false,
        disableActions: ['add', 'addBefore', 'addAfter', 'remove', 'duplicate', 'copy'],
      },
      of: [defineArrayMember({type: 'imageCaption'})],
      validation: (rule) => rule.required().length(44),
    }),
    defineField({
      name: 'imageCaptionsFr',
      title: 'Case study image captions (French)',
      type: 'array',
      group: 'french',
      description: 'Each caption is attached to a permanent image ID. Sorting is disabled.',
      options: {
        sortable: false,
        disableActions: ['add', 'addBefore', 'addAfter', 'remove', 'duplicate', 'copy'],
      },
      of: [defineArrayMember({type: 'imageCaption'})],
      validation: (rule) => rule.required().length(44),
    }),
    defineField({
      name: 'projectCardsEn',
      title: 'Project information cards (English)',
      type: 'array',
      group: 'english',
      description: 'Project order and IDs are fixed by the case study index.',
      options: {
        sortable: false,
        disableActions: ['add', 'addBefore', 'addAfter', 'remove', 'duplicate', 'copy'],
      },
      of: [defineArrayMember({type: 'projectCard'})],
      validation: (rule) => rule.required().length(5),
    }),
    defineField({
      name: 'projectCardsFr',
      title: 'Project information cards (French)',
      type: 'array',
      group: 'french',
      description: 'Project order and IDs are fixed by the case study index.',
      options: {
        sortable: false,
        disableActions: ['add', 'addBefore', 'addAfter', 'remove', 'duplicate', 'copy'],
      },
      of: [defineArrayMember({type: 'projectCard'})],
      validation: (rule) => rule.required().length(5),
    }),
    defineField({
      name: 'residentTopicsEn',
      title: 'Resident topics and quotes (English)',
      type: 'array',
      group: 'english',
      description: 'Topic and quote order, IDs, and counts are fixed by the diagram.',
      options: {
        sortable: false,
        disableActions: ['add', 'addBefore', 'addAfter', 'remove', 'duplicate', 'copy'],
      },
      of: [defineArrayMember({type: 'residentTopic'})],
      validation: (rule) => rule.required().length(6),
    }),
    defineField({
      name: 'residentTopicsFr',
      title: 'Resident topics and quotes (French)',
      type: 'array',
      group: 'french',
      description: 'Topic and quote order, IDs, and counts are fixed by the diagram.',
      options: {
        sortable: false,
        disableActions: ['add', 'addBefore', 'addAfter', 'remove', 'duplicate', 'copy'],
      },
      of: [defineArrayMember({type: 'residentTopic'})],
      validation: (rule) => rule.required().length(6),
    }),
    ...bilingualRichText('conclusion', 'Final essay'),
    defineField({
      name: 'endnotesEn',
      title: 'Final essay notes (English)',
      type: 'array',
      group: 'english',
      options: {
        sortable: false,
        disableActions: ['add', 'addBefore', 'addAfter', 'remove', 'duplicate', 'copy'],
      },
      of: [defineArrayMember({type: 'endnote'})],
      validation: (rule) => rule.required().length(9),
    }),
    defineField({
      name: 'endnotesFr',
      title: 'Final essay notes (French)',
      type: 'array',
      group: 'french',
      options: {
        sortable: false,
        disableActions: ['add', 'addBefore', 'addAfter', 'remove', 'duplicate', 'copy'],
      },
      of: [defineArrayMember({type: 'endnote'})],
      validation: (rule) => rule.required().length(9),
    }),
  ],
  preview: {prepare: () => ({title: 'Post occupancy evaluation page'})},
})
