import {defineArrayMember, defineField, defineType} from 'sanity'
import {bilingualRichText, bilingualString, bilingualText, languageGroups} from '../helpers'

export const postOccupancyPage = defineType({
  name: 'postOccupancyPage',
  title: 'Post occupancy evaluation page',
  type: 'document',
  groups: languageGroups,
  fields: [
    ...bilingualString('title', 'Page title'),
    ...bilingualString('deck', 'Page subtitle'),
    ...bilingualText('introduction', 'Introduction'),
    ...bilingualString('caseStudiesTitle', 'Case studies heading'),
    ...bilingualString('residentVoicesTitle', 'Resident voices heading'),
    ...bilingualText('residentVoicesIntroduction', 'Resident voices introduction'),
    defineField({
      name: 'imageCaptionsEn',
      title: 'Case study image captions (English)',
      type: 'array',
      group: 'english',
      description: 'Each caption is attached to a permanent image ID. Sorting is disabled.',
      options: {sortable: false},
      of: [defineArrayMember({type: 'imageCaption'})],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: 'imageCaptionsFr',
      title: 'Case study image captions (French)',
      type: 'array',
      group: 'french',
      description: 'Each caption is attached to a permanent image ID. Sorting is disabled.',
      options: {sortable: false},
      of: [defineArrayMember({type: 'imageCaption'})],
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: 'projectCardsEn',
      title: 'Project information cards (English)',
      type: 'array',
      group: 'english',
      description: 'Project order and IDs are fixed by the case study index.',
      options: {sortable: false},
      of: [defineArrayMember({type: 'projectCard'})],
      validation: (rule) => rule.required().length(5),
    }),
    defineField({
      name: 'projectCardsFr',
      title: 'Project information cards (French)',
      type: 'array',
      group: 'french',
      description: 'Project order and IDs are fixed by the case study index.',
      options: {sortable: false},
      of: [defineArrayMember({type: 'projectCard'})],
      validation: (rule) => rule.required().length(5),
    }),
    defineField({
      name: 'residentTopicsEn',
      title: 'Resident topics and quotes (English)',
      type: 'array',
      group: 'english',
      description: 'Topic and quote order, IDs, and counts are fixed by the diagram.',
      options: {sortable: false},
      of: [defineArrayMember({type: 'residentTopic'})],
      validation: (rule) => rule.required().length(6),
    }),
    defineField({
      name: 'residentTopicsFr',
      title: 'Resident topics and quotes (French)',
      type: 'array',
      group: 'french',
      description: 'Topic and quote order, IDs, and counts are fixed by the diagram.',
      options: {sortable: false},
      of: [defineArrayMember({type: 'residentTopic'})],
      validation: (rule) => rule.required().length(6),
    }),
    ...bilingualRichText('conclusion', 'Final essay'),
  ],
  preview: {prepare: () => ({title: 'Post occupancy evaluation page'})},
})
