import {defineType} from 'sanity'
import {bilingualString, bilingualText, languageGroups} from '../helpers'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site settings',
  type: 'document',
  groups: languageGroups,
  fields: [
    ...bilingualString('siteTitle', 'Browser title'),
    ...bilingualString('skipLink', 'Skip to main content link'),
    ...bilingualString('introductionNav', 'Introduction navigation label'),
    ...bilingualString('supplyNav', 'Supply navigation label'),
    ...bilingualString('healthNav', 'Health outcomes navigation label'),
    ...bilingualString('postOccupancyNav', 'Post occupancy navigation label'),
    ...bilingualString('resourcesNav', 'News sources navigation label'),
    ...bilingualString('bibliographyNav', 'Bibliography navigation label'),
    ...bilingualString('previousPage', 'Previous page label'),
    ...bilingualString('nextPage', 'Next page label'),
    ...bilingualString('glossaryTitle', 'Glossary heading'),
    ...bilingualString('glossarySocialStockTerm', 'Social rental housing stock term'),
    ...bilingualText('glossarySocialStockDefinition', 'Social rental housing stock definition'),
    ...bilingualString('glossaryQpvTerm', 'Priority urban policy neighborhood term'),
    ...bilingualText('glossaryQpvDefinition', 'Priority urban policy neighborhood definition'),
    ...bilingualString('glossaryFinancingTitle', 'Financing instruments heading'),
    ...bilingualString('glossaryPlai', 'PLAI definition'),
    ...bilingualString('glossaryPlus', 'PLUS definition'),
    ...bilingualString('glossaryPls', 'PLS definition'),
    ...bilingualString('glossaryPli', 'PLI definition'),
    ...bilingualString('glossaryProvidersTitle', 'Social housing providers heading'),
    ...bilingualString('glossaryOph', 'OPH definition'),
    ...bilingualString('glossaryEsh', 'ESH definition'),
    ...bilingualString('glossarySem', 'SEM definition'),
  ],
  preview: {prepare: () => ({title: 'Site settings'})},
})
